import { Component, Input, OnInit, inject, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { ReactiveFormsModule, FormGroup, FormControl, Validators } from '@angular/forms';
import { LabTestFacade } from '@app/features/lab-tests/facade/lab-test.facade';
import { LabTestEntity } from '@app/features/lab-tests/domain/lab-test.entity';

@Component({
  selector: 'app-add-lab-test',
  standalone: true,
  imports: [
    CommonModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatIconModule,
    ReactiveFormsModule,
  ],
  templateUrl: './add-lab-test.component.html',
  styleUrls: ['./add-lab-test.component.css'],
})
export class AddLabTestComponent {
  @Input() patientId: number | undefined;
  @Output() labTestAdded = new EventEmitter<void>();
  @Output() cancel = new EventEmitter<void>();

  private labTestFacade = inject(LabTestFacade);

  labTestForm = new FormGroup({
    labTestName: new FormControl('', Validators.required),
  });

  onSubmit() {
    if (this.labTestForm.valid && this.patientId) {
      const newLabTest: LabTestEntity = new LabTestEntity({
        labTestId: 0, // ID will be generated by the backend
        labTestName: this.labTestForm.value.labTestName!,
        labTestDate:new Date().toISOString().split('T')[0],
        patientId: this.patientId,
      });

      this.labTestFacade.addLabTest(newLabTest);
      this.labTestAdded.emit();
    }
  }
 

  onCancel() {
    this.cancel.emit();
  }
}
